name: BingoLobby
main: com.github.peddach.bingoLobby.BingoLobby
author: Professor_Sam
version: ${project.version}
api-version: 1.19
depend:
   - ViaVersion
   - TurtleServer
commands:
   BingoLobby:
      description: Manage BingoLobby