name: Bingo
main: com.github.peddach.bingoHost.BingoHost
author: Professor_Sam
softdepend:
- Multiverse-Core
- Multiverse-NetherPortals
version: ${project.version}
api-version: 1.19
commands:
   Bingo:
      description: Manage Bingo
   Start:
      description: Startet das Spiel