name: Bingo
main: com.github.peddach.bingoHost.BingoHost
author: Professor_Sam
depend:
   - TurtleServer
version: ${project.version}
api-version: 1.20
commands:
   Bingo:
      description: Manage Bingo
   Start:
      description: Startet das Spiel